version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache

      - run:
          name: 🧐 Lint with flake8
          command: |
            pip3 install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=99 --statistics

      - run:
          name: ⏬ Downloading test repositories
          command: |
            git clone https://github.com/YEmreAk/YLib ../YLib
            git clone https://github.com/YEmreAk/YPython ../YPython
            git clone https://github.com/yedhrab/DarkCode-Theme ../DarkCode-Theme

      - run:
          name: ⚗️ Functional testing
          command: |
            python3 setup.py test
     
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results


# Continuously Deploying Python Packages to PyPI with CircleCI
# https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/

  deploy:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - run:
          name: 🏷️ Verify git tag version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify

      - run:
          name: 🔨 PYPI configuration created
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc

      - run:
          name: 📦 Create PYPI package
          command: |
            python setup.py sdist bdist_wheel

      - run:
          name: ⏫ Upload package to PYPI
          command: |
            twine upload dist/*

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
